# Kakao 설정
kakao:
  client_id: ${KAKAO_CLIENT_ID}
  redirect_uri: http://localhost:8080/api/kakao/callback
  get_code_path: https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=

# MySQL 연결 설정
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# JWT 설정
jwt:
  secret: ${JWT_SECRET}

